name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.2.0)'
        required: true
        default: '1.2.0'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Install Dependencies
        run: |
          npm install -g pnpm@10.12.4
          pnpm install

      # Download and setup FFmpeg for MacOS
      - name: Download FFmpeg for MacOS
        if: matrix.os == 'macos-latest'
        run: |
          # Create ffmpeg directory
          mkdir -p dist-native/ffmpeg
          
          # Download FFmpeg for Intel Mac
          echo "Downloading FFmpeg for Intel Mac..."
          curl -L "https://evermeet.cx/ffmpeg/ffmpeg-6.1.1.zip" -o ffmpeg-intel.zip
          unzip -q ffmpeg-intel.zip
          mv ffmpeg dist-native/ffmpeg/ffmpeg-darwin-x64
          chmod +x dist-native/ffmpeg/ffmpeg-darwin-x64
          
          # Download FFmpeg for Apple Silicon Mac  
          echo "Downloading FFmpeg for Apple Silicon Mac..."
          curl -L "https://www.osxexperts.net/ffmpeg6arm.zip" -o ffmpeg-arm64.zip
          unzip -q ffmpeg-arm64.zip -d ffmpeg-arm64
          # Find the ffmpeg binary in the extracted folder
          find ffmpeg-arm64 -name "ffmpeg" -type f -exec cp {} dist-native/ffmpeg/ffmpeg-darwin-arm64 \;
          chmod +x dist-native/ffmpeg/ffmpeg-darwin-arm64
          
          # Create universal binary
          echo "Creating universal FFmpeg binary..."
          lipo -create dist-native/ffmpeg/ffmpeg-darwin-x64 dist-native/ffmpeg/ffmpeg-darwin-arm64 -output dist-native/ffmpeg/ffmpeg-darwin-universal
          chmod +x dist-native/ffmpeg/ffmpeg-darwin-universal
          
          # Verify binaries
          echo "Verifying FFmpeg binaries..."
          file dist-native/ffmpeg/ffmpeg-darwin-x64
          file dist-native/ffmpeg/ffmpeg-darwin-arm64  
          file dist-native/ffmpeg/ffmpeg-darwin-universal
          
          # Clean up
          rm -f ffmpeg-intel.zip ffmpeg-arm64.zip
          rm -rf ffmpeg-arm64

      # MacOS Build
      - name: Build MacOS
        if: matrix.os == 'macos-latest'
        run: |
          export ELECTRON_BUILDER_EXTRA_ARGS="--universal"
          pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
          DEBUG: electron-builder

      # Windows Build
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Linux Build
      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
          pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Get version from tag or manual input
      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          fi
        shell: bash

      # Read release notes
      - name: Read release notes
        id: release_notes
        run: |
          NOTES=$(awk "/## \[v${{ env.VERSION }}\]/{p=1;print;next} /## \[v/{p=0}p" CHANGELOG.md)
          echo "NOTES<<EOF" >> $GITHUB_ENV
          echo "$NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash

      # Publish Release
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/${{ env.VERSION }}/*.dmg
            release/${{ env.VERSION }}/*.exe
            release/${{ env.VERSION }}/*.deb
            release/${{ env.VERSION }}/*.rpm
            release/${{ env.VERSION }}/*.AppImage
          body: ${{ env.NOTES }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
